// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: mapreduce/reducer.proto

package reducer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapReduce_SendPartition_FullMethodName = "/mapreduce.reducer.MapReduce/SendPartition"
	MapReduce_GetRange_FullMethodName      = "/mapreduce.reducer.MapReduce/GetRange"
)

// MapReduceClient is the client API for MapReduce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MapReduce Service
type MapReduceClient interface {
	// Send an ordered chunk
	SendPartition(ctx context.Context, in *Partition, opts ...grpc.CallOption) (*Ack, error)
	// Requires a range-based partition of a reducer
	GetRange(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*ReducerRequest, error)
}

type mapReduceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapReduceClient(cc grpc.ClientConnInterface) MapReduceClient {
	return &mapReduceClient{cc}
}

func (c *mapReduceClient) SendPartition(ctx context.Context, in *Partition, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MapReduce_SendPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceClient) GetRange(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*ReducerRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReducerRequest)
	err := c.cc.Invoke(ctx, MapReduce_GetRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapReduceServer is the server API for MapReduce service.
// All implementations must embed UnimplementedMapReduceServer
// for forward compatibility.
//
// MapReduce Service
type MapReduceServer interface {
	// Send an ordered chunk
	SendPartition(context.Context, *Partition) (*Ack, error)
	// Requires a range-based partition of a reducer
	GetRange(context.Context, *NodeName) (*ReducerRequest, error)
	mustEmbedUnimplementedMapReduceServer()
}

// UnimplementedMapReduceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapReduceServer struct{}

func (UnimplementedMapReduceServer) SendPartition(context.Context, *Partition) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPartition not implemented")
}
func (UnimplementedMapReduceServer) GetRange(context.Context, *NodeName) (*ReducerRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRange not implemented")
}
func (UnimplementedMapReduceServer) mustEmbedUnimplementedMapReduceServer() {}
func (UnimplementedMapReduceServer) testEmbeddedByValue()                   {}

// UnsafeMapReduceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapReduceServer will
// result in compilation errors.
type UnsafeMapReduceServer interface {
	mustEmbedUnimplementedMapReduceServer()
}

func RegisterMapReduceServer(s grpc.ServiceRegistrar, srv MapReduceServer) {
	// If the following call pancis, it indicates UnimplementedMapReduceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapReduce_ServiceDesc, srv)
}

func _MapReduce_SendPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Partition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).SendPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduce_SendPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).SendPartition(ctx, req.(*Partition))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduce_GetRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).GetRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduce_GetRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).GetRange(ctx, req.(*NodeName))
	}
	return interceptor(ctx, in, info, handler)
}

// MapReduce_ServiceDesc is the grpc.ServiceDesc for MapReduce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapReduce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapreduce.reducer.MapReduce",
	HandlerType: (*MapReduceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPartition",
			Handler:    _MapReduce_SendPartition_Handler,
		},
		{
			MethodName: "GetRange",
			Handler:    _MapReduce_GetRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mapreduce/reducer.proto",
}
