// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: mapreduce/mapreduce.proto

package mapreduce

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data of a chunk to be processed
type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"` // List of integers
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_mapreduce_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_mapreduce_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ordered data of a partition
type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortedData []int32 `protobuf:"varint,1,rep,packed,name=sorted_data,json=sortedData,proto3" json:"sorted_data,omitempty"` // Ordered data
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_mapreduce_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_mapreduce_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *Partition) GetSortedData() []int32 {
	if x != nil {
		return x.SortedData
	}
	return nil
}

// Confirmation Message
type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Confirmation Message
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_mapreduce_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_mapreduce_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Node name
type NodeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Node name mapper/reducer
}

func (x *NodeName) Reset() {
	*x = NodeName{}
	mi := &file_mapreduce_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeName) ProtoMessage() {}

func (x *NodeName) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeName.ProtoReflect.Descriptor instead.
func (*NodeName) Descriptor() ([]byte, []int) {
	return file_mapreduce_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *NodeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Requesting a reducer
type ReducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                          // Name of reducer
	MinRange int32  `protobuf:"varint,2,opt,name=min_range,json=minRange,proto3" json:"min_range,omitempty"` // Gamma minima
	MaxRange int32  `protobuf:"varint,3,opt,name=max_range,json=maxRange,proto3" json:"max_range,omitempty"` // Maximum range
}

func (x *ReducerRequest) Reset() {
	*x = ReducerRequest{}
	mi := &file_mapreduce_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerRequest) ProtoMessage() {}

func (x *ReducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerRequest.ProtoReflect.Descriptor instead.
func (*ReducerRequest) Descriptor() ([]byte, []int) {
	return file_mapreduce_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *ReducerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReducerRequest) GetMinRange() int32 {
	if x != nil {
		return x.MinRange
	}
	return 0
}

func (x *ReducerRequest) GetMaxRange() int32 {
	if x != nil {
		return x.MaxRange
	}
	return 0
}

var File_mapreduce_mapreduce_proto protoreflect.FileDescriptor

var file_mapreduce_mapreduce_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x6d, 0x61, 0x70, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x61, 0x70,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x1f, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x32, 0xae, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x13, 0x2e, 0x6d,
	0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x2d, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x10, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x41,
	0x63, 0x6b, 0x12, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x15, 0x5a, 0x13, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2f, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mapreduce_mapreduce_proto_rawDescOnce sync.Once
	file_mapreduce_mapreduce_proto_rawDescData = file_mapreduce_mapreduce_proto_rawDesc
)

func file_mapreduce_mapreduce_proto_rawDescGZIP() []byte {
	file_mapreduce_mapreduce_proto_rawDescOnce.Do(func() {
		file_mapreduce_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapreduce_mapreduce_proto_rawDescData)
	})
	return file_mapreduce_mapreduce_proto_rawDescData
}

var file_mapreduce_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mapreduce_mapreduce_proto_goTypes = []any{
	(*Chunk)(nil),          // 0: mapreduce.Chunk
	(*Partition)(nil),      // 1: mapreduce.Partition
	(*Ack)(nil),            // 2: mapreduce.Ack
	(*NodeName)(nil),       // 3: mapreduce.NodeName
	(*ReducerRequest)(nil), // 4: mapreduce.ReducerRequest
}
var file_mapreduce_mapreduce_proto_depIdxs = []int32{
	3, // 0: mapreduce.MapReduce.GetChunk:input_type -> mapreduce.NodeName
	0, // 1: mapreduce.MapReduce.SendChunk:input_type -> mapreduce.Chunk
	4, // 2: mapreduce.MapReduce.GetPartition:input_type -> mapreduce.ReducerRequest
	0, // 3: mapreduce.MapReduce.GetChunk:output_type -> mapreduce.Chunk
	2, // 4: mapreduce.MapReduce.SendChunk:output_type -> mapreduce.Ack
	1, // 5: mapreduce.MapReduce.GetPartition:output_type -> mapreduce.Partition
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mapreduce_mapreduce_proto_init() }
func file_mapreduce_mapreduce_proto_init() {
	if File_mapreduce_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapreduce_mapreduce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapreduce_mapreduce_proto_goTypes,
		DependencyIndexes: file_mapreduce_mapreduce_proto_depIdxs,
		MessageInfos:      file_mapreduce_mapreduce_proto_msgTypes,
	}.Build()
	File_mapreduce_mapreduce_proto = out.File
	file_mapreduce_mapreduce_proto_rawDesc = nil
	file_mapreduce_mapreduce_proto_goTypes = nil
	file_mapreduce_mapreduce_proto_depIdxs = nil
}
