// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: mapreduce/mapreduce.proto

package mapreduce

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapReduce_GetChunk_FullMethodName     = "/mapreduce.MapReduce/GetChunk"
	MapReduce_SendChunk_FullMethodName    = "/mapreduce.MapReduce/SendChunk"
	MapReduce_GetPartition_FullMethodName = "/mapreduce.MapReduce/GetPartition"
)

// MapReduceClient is the client API for MapReduce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MapReduce Service
type MapReduceClient interface {
	// Retrieve a chunk for processing
	GetChunk(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*Chunk, error)
	// Send an ordered chunk
	SendChunk(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Ack, error)
	// Requires a range-based partition of a reducer
	GetPartition(ctx context.Context, in *ReducerRequest, opts ...grpc.CallOption) (*Partition, error)
}

type mapReduceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapReduceClient(cc grpc.ClientConnInterface) MapReduceClient {
	return &mapReduceClient{cc}
}

func (c *mapReduceClient) GetChunk(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*Chunk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chunk)
	err := c.cc.Invoke(ctx, MapReduce_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceClient) SendChunk(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MapReduce_SendChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceClient) GetPartition(ctx context.Context, in *ReducerRequest, opts ...grpc.CallOption) (*Partition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Partition)
	err := c.cc.Invoke(ctx, MapReduce_GetPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapReduceServer is the server API for MapReduce service.
// All implementations must embed UnimplementedMapReduceServer
// for forward compatibility.
//
// MapReduce Service
type MapReduceServer interface {
	// Retrieve a chunk for processing
	GetChunk(context.Context, *NodeName) (*Chunk, error)
	// Send an ordered chunk
	SendChunk(context.Context, *Chunk) (*Ack, error)
	// Requires a range-based partition of a reducer
	GetPartition(context.Context, *ReducerRequest) (*Partition, error)
	mustEmbedUnimplementedMapReduceServer()
}

// UnimplementedMapReduceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapReduceServer struct{}

func (UnimplementedMapReduceServer) GetChunk(context.Context, *NodeName) (*Chunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedMapReduceServer) SendChunk(context.Context, *Chunk) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChunk not implemented")
}
func (UnimplementedMapReduceServer) GetPartition(context.Context, *ReducerRequest) (*Partition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartition not implemented")
}
func (UnimplementedMapReduceServer) mustEmbedUnimplementedMapReduceServer() {}
func (UnimplementedMapReduceServer) testEmbeddedByValue()                   {}

// UnsafeMapReduceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapReduceServer will
// result in compilation errors.
type UnsafeMapReduceServer interface {
	mustEmbedUnimplementedMapReduceServer()
}

func RegisterMapReduceServer(s grpc.ServiceRegistrar, srv MapReduceServer) {
	// If the following call pancis, it indicates UnimplementedMapReduceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapReduce_ServiceDesc, srv)
}

func _MapReduce_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduce_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).GetChunk(ctx, req.(*NodeName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduce_SendChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).SendChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduce_SendChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).SendChunk(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduce_GetPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).GetPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduce_GetPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).GetPartition(ctx, req.(*ReducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapReduce_ServiceDesc is the grpc.ServiceDesc for MapReduce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapReduce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapreduce.MapReduce",
	HandlerType: (*MapReduceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChunk",
			Handler:    _MapReduce_GetChunk_Handler,
		},
		{
			MethodName: "SendChunk",
			Handler:    _MapReduce_SendChunk_Handler,
		},
		{
			MethodName: "GetPartition",
			Handler:    _MapReduce_GetPartition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mapreduce/mapreduce.proto",
}
